config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: { registrations: 'members/registrations',
  passwords: 'members/passwords' }
  root to: 'pages#home'
  resources :members do
    resource :account
  end
  get 'about', to: 'pages#about'
  get 'loyalty', to: 'pages#loyalty'
  resources 'menu'
  get 'location', to: 'pages#location' 
end

app/models/account.rb
class Account < ApplicationRecord
    validates :visit_count, presence: true, numericality: true
    validates :loyalty_points, presence: true, numericality: true
    validates :card_number, presence: true, numericality: true, uniqueness: true
    validates :join_date, presence: true
    validates :last_visit, presence: true
    

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :accounts
  
  validates :card_number, presence: true, numericality: true, uniqueness: true

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  validates :category, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # Comment out to create example Loyalty Accounts
  before_action :authenticate_member!
  before_action :only_current_member
  
  # New and create actions should happen when card is used
  def new
    @account = Account.new
  end
  
  def create
    @account = Account.new(account_params)
    @account.save
  end
  
  # GET to members/:member_id/account
  def show
    @card = current_member.card_number
    
    # Link Member to Account by Loyalty Card number upon first login
    if Account.where( "card_number = ?", "#{@card}" ).where( :member_id => nil ).exists?
      # Find loyalty account with matching card no.
      @accounts = Account.where( "card_number = ?", "#{@card}" )
      # Link loyalty account to member with matching card no.
      @accounts.update_all(member_id: "#{current_member.id}")
      reg_point = @accounts.find_by(member_id: "#{current_member.id}")
      reg_point.update(loyalty_points: "#{reg_point.loyalty_points + 1}")
    end
    
    @account = Account.find_by("member_id = ?", "#{current_member.id}")
    @punches = @account.visit_count.digits.first
  end
  
  def update
    @account = Account.find_by("member_id = ?", "#{current_member.id}")
    @account.update_attributes( update_params )
    redirect_to loyalty_path
  end

  private
    # Redirects user to their own account if they try to modify URL params
    def only_current_member
      if "#{current_member.id}" != "#{params[:member_id]}"
        redirect_to member_account_path(current_member.id)
      end
    end
    
    def account_params
      params.require(:account).permit(:visit_count, :loyalty_points, :card_number, :join_date, :last_visit)
    end
    
    def update_params
      params.require(:account).permit(:first_name, :last_name, :birthday)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  
  private
    # Allows additional categories for Devise sign up form
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:card_number])
    end
    
    # Redirect to loyalty_path when loyalty member signs up/in
    def after_sign_in_path_for(members)
      @member = current_member.id
      member_account_path( member_id: @member )
    end
    
    
    # Redirect to loyalty_path when loyalty member signs out
    def after_sign_out_path_for(members)
      loyalty_path
    end  
end

app/controllers/members/passwords_controller.rb
class Members::PasswordsController < Devise::PasswordsController

  # POST /resource/password
  def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)
    yield resource if block_given?

    if successfully_sent?(resource)
      respond_with({}, location: after_sending_reset_password_instructions_path_for(resource_name))
    else
      flash.now[:danger] = "Uh Oh! We've run into a problem... 
        #{resource.errors.full_messages.join(", ")}"
      respond_with(resource)
      
    end
  end

end

app/controllers/members/registrations_controller.rb
class Members::RegistrationsController < Devise::RegistrationsController
  
  # POST /members, overrides devise controller
  def create
    build_resource(sign_up_params)
    
    if account_exists?
      resource.save
      
        yield resource if block_given?
        
        if resource.persisted?
          if resource.active_for_authentication?
            set_flash_message! :success, :signed_up
            sign_up(resource_name, resource)
            respond_with resource, location: after_sign_up_path_for(resource)
          else
            set_flash_message! :danger, :"signed_up_but_#{resource.inactive_message}"
            expire_data_after_sign_in!
            respond_with resource, location: after_inactive_sign_up_path_for(resource)
          end
        else
          # Displays sign up errors in flash
          flash.now[:danger] = "Uh Oh! We weren't able to sign you up...
            #{resource.errors.full_messages.join(", ")}"
          clean_up_passwords resource
          set_minimum_password_length
          respond_with resource
        end
      
      else
        if resource.errors != nil
          flash.now[:danger] = "Uh Oh! We weren't able to sign you up...
           That Loyalty Account doesnt exist!"
        end
        clean_up_passwords resource
        set_minimum_password_length
        render action: 'new'
    end  
  
  end
  
  private
    def account_exists?
      !(Account.where( "card_number = ?" , "#{params[:member][:card_number]}").empty?)
    end
  
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  
  # Requires admin access
  def new
    @menu_item = Menu.new
  end
  
  
  def create
      @menu_item = Menu.new(menu_params)
      
      if @menu_item.save
        flash[:success] = "New Menu item saved!"
        redirect_to new_menu_path
      else
        flash[:danger] = @menu_item.errors.full_messages.join(", ")
        redirect_to new_menu_path
      end
    
  end
  
  
  def index
    # When user chooses a category option from dropdown menu 
    if params[:commit]
      @category = params[:category]
      # Clean up URL in user view and redirect to index
      redirect_to menu_index_path( type: @category )
    # If user has selectd a category and been redirected
    elsif params[:type]
      @menu_item = Menu.all
      # Assign desired items to display_menu, sanitize query params
      @display_menu = @menu_item.where( "category = ?", params[:type] )
    end
  end
  
  private
    def menu_params
      params.require(:menu).permit(:category, :name, :price, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  # GET to / 
  def home
  end
  
  # GET to /about
  def about
  end
  
  # GET to /loyalty
  def loyalty
    if member_signed_in?
      redirect_to member_account_path( member_id: current_member.id)
    end
  end
  
  # GET to /location
  def location
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_personal_info_form.html.erb
<%= "Tell us about yourself!" %>
  <%= form_for @account, url: member_account_path, html: {method: :put} do |f| %>
    <div class="field form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>
    </div>
    <div class="field form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>
    </div>
    <div class="field form-group">
      <%= f.label :birthday %>
      <%= f.date_field :birthday, class: 'form-control' %>
    </div>
    <div class="actions form-group">
      <%= f.submit "submit", class: 'btn btn-primary' %>
    </div>
  <% end %>

app/views/accounts/_rewards.html.erb
<div class="well row">

  <div class="col-sm-6 loyalty-left">
    <%= "Visits: #{@account.visit_count}" %><br>
    <% if @account.visit_count == 1 %>
      <%= "Bronze Member" %><br>
    <% elsif @account.visit_count <= 20 %>
      <%= "Silver Member" %><br>
    <% elsif @account.visit_count > 20 %>
      <%= "Gold Member" %><br>
    <% end %>
    
    <% if @account.loyalty_points == "1" %>
      <%= "You have credit for #{@account.loyalty_points} free slice!" %><br>
    <% else %>
      <%= "You have credit for #{@account.loyalty_points} free slices!" %><br>
    <% end %>
  </div>
 
  <div class="col-sm-6 loyalty-right">
    <h3 class="text-center"><%= "#{10 - @punches} visits until your next reward!" %></h3>
    <div class="well loyalty col-sm-offset-2">
      <% @punches.times do || %>
        <i class="material-icons md-36 red-punch">local_pizza</i>
      <% end %>
      <% (10 - @punches).times do || %>
        <i class="material-icons md-36 gray-punch">local_pizza</i>
      <% end %><br>
    </div>
  </div>
   
</div>

app/views/accounts/edit.html.erb
Edit Path

app/views/accounts/new.html.erb
<%= form_for @account, url: member_account_path do |f| %>
  <div class="form-group">
    <%= f.label :visit_count %>
    <%= f.text_field :visit_count, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :loyalty_points %>
    <%= f.text_field :loyalty_points, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :card_number %>
    <%= f.text_field :card_number, class: 'form-control' %>
  </div> 
  <div class="form-group">
    <%= f.label :join_date %>
    <%= f.date_field :join_date, class: 'form-control' %>
  </div> 
  <div class="form-group">
    <%= f.label :last_visit %>
    <%= f.date_field :last_visit, class: 'form-control' %>
  </div> 
  <div>
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>
  

app/views/accounts/show.html.erb
<% content_for :title, "Loyalty" %>

<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h2 class="text-center">Your Account</h2><br>
          
      <% if @account.first_name.blank? or @account.last_name.blank? or @account.birthday.blank?  %>
        <%= render "personal_info_form" %>
      <% else %>
        <%= "Hi #{@account.first_name} #{@account.last_name}!" %><br>
      <% end %>
      
      <%= render "rewards" %> 

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "Maggies | #{yield(:title)}" %></title>
    
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">  
    <link href="https://fonts.googleapis.com/css?family=Dosis:400,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= favicon_link_tag 'favicon.png' %>
    <!-- Dynamic viewing on mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: 'navbar-brand' do %>
            <i class="material-icons">local_pizza</i>
            Maggie's
          <% end %>
        </div>
        
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if member_signed_in? %>
              <%= link_to "Sign Out", destroy_member_session_path, method: :delete, class: 'btn btn-primary navbar-btn' %>
            <% end %>
            <li><%= link_to "Menu", menu_index_path %></li>
            <li><%= link_to "Locations", location_path %></li>
            <li><%= link_to "Loyalty", loyalty_path %></li>
            <li><%= link_to "About Us", about_path %></li>
          </div>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>

    <div class="container flash-container">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{type}" %>
      <% end %>
    <div>
    <%= yield %>

  </body>
</html>

app/views/menu/_menu_form.html.erb
<%= form_for @menu_item, url: {action: "create"} do |f| %>
  <div class="form-group">
    <%= f.label :category %>
    <%= f.select :category, ['Appetizer', 'Salad/Soup', 'Pizza', 'Pasta', 'Sandwiches', 'Desert'], class: 'form-control', :include_blank => true %>
  </div>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, autocomplete: "off", class: 'form-control' %> 
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, autocomplete: "off", class: 'form-control' %>
  </div> 
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="actions form-group">
    <%= f.submit 'Submit', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/menu/index.html.erb
<% content_for :title, "Menu" %>

<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
          <!-- Dropdown to select Menu category-->
          <%= form_tag menu_index_path, method: "get", class: "form-menu" do %>
            <%= select_tag 'category', options_for_select(['Appetizer', 'Salad/Soup', 'Pizza', 'Pasta', 'Sandwiches', 'Desert']), class: 'form-control form-group' %>
            <%= submit_tag 'Submit', class: 'btn btn-primary' %>
          <% end %>

      <!-- If category has not been selected -->
      <% if !@display_menu %>
        <%= "Choose a category" %>
      <!-- If category has been selected -->  
      <% else %> 
        <h2 class="text-center"><%= @category %></h2>
        <% @display_menu.each do |item| %>
          <div class="well">  
            <h3><%= item.name %></h2>
            <p>$<%= item.price %></p>
            <p><%= item.description %></p>
          </div>
        <% end %>
      <% end %>
      
      <!-- Temporary link for development -->
      <%= link_to "Create Menu Item", new_menu_path, class: 'btn btn-primary' %>

    </div>
  </div>
</div>

app/views/menu/new.html.erb
<!-- Must be an Admin to use this function -->
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h2>Create a new Menu item!</h2>
        <div class="well">
          <%= render "menu_form" %>
        </div>
    </div>
  </div>  
</div>

app/views/pages/_about.html.erb
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate, fugit,
impedit, est, iure ipsum earum hic quisquam itaque eos aspernatur fugiat minus
eligendi ipsam recusandae neque inventore cumque delectus quas.</p>

app/views/pages/about.html.erb
<% content_for :title, "About" %>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render "about" %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<% content_for :title, "Home" %>

<div class="home-callout text-center container-fluid">
  <h1>Welcome to Maggie's Pizza!</h1>
  <h3>Home of the Maggie's Favorie Special!</h3>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h2 class="text-center">What's Happening</h2>
        <div class="well-border">
          <div class="well">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos, tenetur, molestias a aperiam voluptatum non architecto temporibus officia nulla vitae beatae repellat soluta accusantium nisi quidem officiis laborum quis ea.</p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <h2 class="text-center">About Us</h2>
        <div class="well">
          <%= render "about" %>
        </div>
    </div>
  </div>
</div>

app/views/pages/location.html.erb
<% content_for :title, "Locations" %>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h2 class="text-center">Locations page</h2>

      <div class="embed-responsive embed-responsive-4by3">
        <iframe class="embed-responsive-item"
          frameborder="0" style="border:0"
          src="https://www.google.com/maps/embed/v1/place?key=AIzaSyC6QFPRah2wLzGKDoiptfQAxDFyNb4gSnU
            &q=Space+Needle,Seattle+WA" allowfullscreen>
        </iframe>
      </div>  

    </div>
  </div>
</div>

app/views/pages/loyalty.html.erb
<% content_for :title, "Loyalty" %>

  <div class="container">
    <div class="row">
      <div class="col col-md-6 col-md-offset-3 text-center">
        <h2>Loyalty Program</h2>
        <h3>Sign in or sign up to view your loyalty accout!</p>
      </div>
      <div class="col col-md-4 col-md-offset-2">
        <div class="well text-center">
          <h3>Log in!</h3>
          <p> Log into your Maggie's loyalty acctount and view your rewards!</p>
          <%= link_to "Log In", new_member_session_path, class: 'btn btn-primary' %>
        </div>
      </div>
       <div class="col col-md-4" >
        <div class="well text-center">
          <h3>Register Now!</h3>
          <p> Register your Maggie's loyalty account today and join the club!</p>
          <%= link_to "Register", new_member_registration_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>